export default [
  { text: "formica cocina", value: 100 },
  { text: "formica para cocina", value: 79 },
  { text: "formaica", value: 51 },
  { text: "formica madera", value: 50 },
  { text: "formica precio", value: 47 },
  { text: "formica home depot", value: 33 },
  { text: "melamina", value: 28 },
  { text: "formica para madera", value: 21 },
  { text: "formica blanca", value: 18 },
  { text: "formica para cocinas", value: 18 },
  { text: "mdf", value: 16 },
  { text: "cubierta para cocina", value: 16 },
  { text: "cubiertas para cocina", value: 13 },
  { text: "formica para cocina home depot", value: 10 },
  { text: "formica mexico", value: 10 },
  { text: "formica tipo marmol", value: 7 },
  { text: "cubiertas para cocinas integrales de formica", value: 6 },
  { text: "mauro formica", value: 5 },
  { text: "formaica en home depot", value: 4 },
  { text: "melamina blanca", value: 3 },
  { text: "cubiertas para cocina baratas", value: 1 },
];
